server:
  port: 31111
spring:
  application:
    name: util-freemarker
  data:
    mongodb:
      uri:  mongodb://root:r00t12345@localhost:27017
      database: xc_cms
     # authentication-database: admin