server:
  port: 31000
spring:
  application:
    name: xc-service-manage-cms-client
  data:
    mongodb:
      uri:  mongodb://root:r00t12345@localhost:27017
      database: xc_cms
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: /
xuecheng:
  mq:
    exchange: ex_routing_cms_postpage #cms交换机的名称
    queue: queue_cms_postpage_01  #cms客户端监控的队列名称（不同的客户端监控的队列不能重复）
    routingKey: 5a751fab6abb5044e0d19ea1  #此routingKey为门户站点Cms_Site的ID值